import js from "@eslint/js";
import prettier from "eslint-config-prettier";
import svelte from "eslint-plugin-svelte";
import svelteParser from "svelte-eslint-parser";
import globals from "globals";
import ts from "typescript-eslint";

export default ts.config(
  js.configs.recommended,
  ...ts.configs.strictTypeChecked,
  ...ts.configs.stylisticTypeChecked,
  ...svelte.configs.recommended,
  prettier,
  ...svelte.configs.prettier,
  {
    languageOptions: {
      parserOptions: {
        projectService: true,
        extraFileExtensions: [".svelte"],
        tsconfigRootDir: import.meta.dirname,
      },
      globals: {
        ...globals.browser,
        ...globals.node,
      },
    },
    rules: {
      "@typescript-eslint/no-unused-vars": [
        "error",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
        },
      ],
      "@typescript-eslint/no-explicit-any": "error",
      "@typescript-eslint/explicit-function-return-type": ["error", { allowExpressions: true }],
      "@typescript-eslint/consistent-type-imports": ["error", { fixStyle: "inline-type-imports" }],
      "@typescript-eslint/switch-exhaustiveness-check": "error",
      // CLAUDE.md 5.7: regex is a last resort, and Japanese text makes hand-written
      // character classes wrong in ways that only show up on rare input.
      "prefer-regex-literals": "error",
      "no-console": ["error", { allow: ["warn", "error"] }],
      eqeqeq: ["error", "always", { null: "ignore" }],
      "no-undef": "off",
      // SvelteKit type-safe routes via resolve() are not used in this project.
      "svelte/no-navigation-without-resolve": "off",
    },
  },
  {
    files: ["**/*.svelte", "**/*.svelte.ts", "**/*.svelte.js"],
    languageOptions: {
      parser: svelteParser,
      parserOptions: {
        parser: ts.parser,
        projectService: true,
        extraFileExtensions: [".svelte"],
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      // Svelte components have many inline event handlers and reactive functions.
      "@typescript-eslint/explicit-function-return-type": "off",
    },
  },
  {
    // Corpus preprocessing runs under bun outside the app, and prints progress.
    files: ["scripts/**/*.ts"],
    rules: {
      "no-console": "off",
    },
  },
  {
    files: ["drizzle/**/*.ts"],
    rules: {
      // Drizzle's column builders carry their whole configuration in the type,
      // several generics deep, and the names change between releases. Spelling
      // them out would pin the schema to one version of Drizzle's internals.
      "@typescript-eslint/explicit-function-return-type": "off",
    },
  },
  {
    files: ["src/lib/components/ui/**/*.svelte", "src/lib/components/ui/**/*.ts"],
    rules: {
      // Generated by shadcn-svelte. These would resurface on every component re-add,
      // so treat the directory as vendored rather than rewriting it.
      "@typescript-eslint/no-useless-default-assignment": "off",
      "@typescript-eslint/no-unsafe-assignment": "off",
      "@typescript-eslint/prefer-nullish-coalescing": "off",
      "@typescript-eslint/no-unsafe-member-access": "off",
      "@typescript-eslint/no-unsafe-call": "off",
      "@typescript-eslint/no-unsafe-argument": "off",
      "@typescript-eslint/no-unsafe-return": "off",
      "@typescript-eslint/no-confusing-void-expression": "off",
      "@typescript-eslint/no-unnecessary-condition": "off",
    },
  },
  {
    // Tool configuration at the repo root, outside any tsconfig. neon.ts is one
    // of these in everything but name.
    files: ["*.config.{js,ts}", "*.config.*.{js,ts}", "neon.ts", "middleware.ts"],
    languageOptions: {
      parserOptions: {
        projectService: false,
      },
    },
    extends: [ts.configs.disableTypeChecked],
  },
  {
    ignores: [
      // Claude Code's own folder: settings, and git worktrees of this repo
      // that background work happens in, which get linted where they live.
      ".claude/",
      ".svelte-kit/",
      "build/",
      "node_modules/",
      // Generated output, not source. See CLAUDE.md 3.4.
      "src/lib/paraglide/",
      "static/corpus/",
    ],
  },
);
